name: "Lint"

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
  

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt-get install pylint3
      - name: Run linter
        run: |
          ls -al
          pylint3 *.py
