name: "On push or PR to master"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt-get install pylint3
          pip3 install -r requirements.txt
          pip3 install pytest
      - name: Run linter
        run: pylint3 wheatley/**/*.py
      - name: Run tests
        run: python3 -m pytest
      - name: Check version string consistency
        run: ./check-version-strings
