name: "Lint"

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master
  

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip3 install pylint
    - name: Run linter
      run: python -m pylint *.py
