name: "Testing/Linting/Fuzzing"

on:
  pull_request:
    branches:
      - master
      - release/*
  push:
    branches:
      - master
      - release/*
  

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt-get install pylint3
          pip3 install -r requirements.txt
          pip3 install pytest
      - name: Run linter
        run: pylint3 wheatley/**/*.py
      - name: Run tests
        run: python3 -m pytest
      - name: Run fuzzer
        run: ./fuzz
